name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" 

jobs:
  test:
    name: "TestDriver - ${{ matrix.city }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - city: Austin
            website_url: https://www.builtinaustin.com/
          - city: Boston
            website_url: https://www.builtinboston.com/
          - city: Chicago
            website_url: https://www.builtinchicago.org/
          - city: Denver
            website_url: https://www.builtincolorado.com/
          - city: Los Angeles
            website_url: https://www.builtinla.com/
          - city: New York City
            website_url: https://www.builtinnyc.com/
          - city: Seattle
            website_url: https://www.builtinseattle.com/
          - city: San Francisco
            website_url: https://www.builtinsf.com/

    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run testdriver/testdriver.yml false false
          prerun: |
            (gc ./testdriver/testdriver.yml) -replace "TD_CITY", '${{ matrix.city }}' | sc -Force ./testdriver/testdriver.yml
            cd $env:TEMP
            npm init -y
            npm install dashcam-chrome
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ matrix.website_url }}"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          WEBSITE_URL: ${{ matrix.website_url }}
